### PR TITLE
fix bug:'FALSE' was not declared in SetOpt

### PR DESCRIPTION
**Pull request by zlinwei**
compile on ubuntu 18.04

curlpp/src/curlpp/internal/OptionSetter.cpp:207:37: error: ‘FALSE’ was not declared in this scope
  handle->option(CURLOPT_NOPROGRESS, FALSE);

### CODE REVIEW

**Comment by sgallou** [comment]
Hi,
thanks for your contribution, but I have 2 comments :

- Instead of redefining TRUE/FALSE constants, use the LibUsb expected value (at curl_easy_setopt call for CURLOPT_NOPROGRESS parameter). Here is "0L" ([see LibUsb documentation](https://curl.haxx.se/libcurl/c/CURLOPT_NOPROGRESS.html))
- Don't forget to update the same function using Boost Progress Function (still in OptionSetter.cpp at line 219)

Thanks

**Comment by zlinwei** [comment]
ok
